version: "3"
services:
    tradingdashboard:
        image: tradingdashboard
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        volumes:
            - ./:/app
        command: bash -c "streamlit run main.py --browser.serverAddress localhost"
