version: "3"
services:
    tradingdashboard:
        image: tradingdashboard
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8051:8501"
        volumes:
            - ./:/app
        command: bash -c "streamlit run main.py"
